language: php

php:
    - 7.0
    - 7.1

before_install:
    - rm .env
    - cp .env.travis .env
    - mysql -e 'CREATE DATABASE arcturus;'
    - composer self-update
    - composer install --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

branches:
    only:
    - development
    - master

services:
  - mysql